name: pytest
on: workflow_dispatch

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/tAIchance/github-action-1
          cd github-action-1
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest